In [1]:
#Dependencies
import pandas as pd
import numpy as np
import json
import pprint as pprint
import sqlalchemy

In [2]:
#Import first data source- LINKS SMALL
links_file = "../ETL_Project_original_Data/links_small.csv"
links_df = pd.read_csv(links_file)

#links_df
#links_df.dtypes
#links_df.columns
links_df=pd.DataFrame(links_df)
links_df

      movieId   imdbId    tmdbId
0           1   114709     862.0
1           2   113497    8844.0
2           3   113228   15602.0
3           4   114885   31357.0
4           5   113041   11862.0
5           6   113277     949.0
6           7   114319   11860.0
7           8   112302   45325.0
8           9   114576    9091.0
9          10   113189     710.0
10         11   112346    9087.0
11         12   112896   12110.0
12         13   112453   21032.0
13         14   113987   10858.0
14         15   112760    1408.0
15         16   112641     524.0
16         17   114388    4584.0
17         18   113101       5.0
18         19   112281    9273.0
19         20   113845   11517.0
20         21   113161    8012.0
21         22   112722    1710.0
22         23   112401    9691.0
23         24   114168   12665.0
24         25   113627     451.0
25         26   114057   16420.0
26         27   114011    9263.0
27         28   114117   17015.0
28         29   112682     902.0
29         30   115012   37557.0
...       ...      ...       ...
9095   159690  3949660  308531.0
9096   159755  3960412  341012.0
9097   159858  3065204  259693.0
9098   159972  2674430  328429.0
9099   160080  1289401   43074.0
9100   160271  1489889  302699.0
9101   160438  4196776  324668.0
9102   160440  2263814  278348.0
9103   160563   918940  258489.0
9104   160565  4094724  316727.0
9105   160567  2823054  316023.0
9106   160590  2751904  177869.0
9107   160656  1639084  353571.0
9108   160718  5613056  399106.0
9109   160954  3531824  328387.0
9110   161084  4465220  368620.0
9111   161155  5794766  401387.0
9112   161336  5278462  373348.0
9113   161582  2582782  338766.0
9114   161594  5595168  390734.0
9115   161830  3732950  314420.0
9116   161918  4831420  390989.0
9117   161944   255313  159550.0
9118   162376  4574334  410612.0
9119   162542  5165344  392572.0
9120   162672  3859980  402672.0
9121   163056  4262980  315011.0
9122   163949  2531318  391698.0
9123   164977    27660  137608.0
9124   164979  3447228  410803.0

[9125 rows x 3 columns]

In [3]:
#Import second data source- RATINGS 
ratings_file = "../ETL_Project_original_Data/ratings_small.csv"
ratings_df = pd.read_csv(ratings_file)

ratings_df=pd.DataFrame(ratings_df)
ratings_df

        userId  movieId  rating   timestamp
0            1       31     2.5  1260759144
1            1     1029     3.0  1260759179
2            1     1061     3.0  1260759182
3            1     1129     2.0  1260759185
4            1     1172     4.0  1260759205
5            1     1263     2.0  1260759151
6            1     1287     2.0  1260759187
7            1     1293     2.0  1260759148
8            1     1339     3.5  1260759125
9            1     1343     2.0  1260759131
10           1     1371     2.5  1260759135
11           1     1405     1.0  1260759203
12           1     1953     4.0  1260759191
13           1     2105     4.0  1260759139
14           1     2150     3.0  1260759194
15           1     2193     2.0  1260759198
16           1     2294     2.0  1260759108
17           1     2455     2.5  1260759113
18           1     2968     1.0  1260759200
19           1     3671     3.0  1260759117
20           2       10     4.0   835355493
21           2       17     5.0   835355681
22           2       39     5.0   835355604
23           2       47     4.0   835355552
24           2       50     4.0   835355586
25           2       52     3.0   835356031
26           2       62     3.0   835355749
27           2      110     4.0   835355532
28           2      144     3.0   835356016
29           2      150     5.0   835355395
...        ...      ...     ...         ...
99974      671     4034     4.5  1064245493
99975      671     4306     5.0  1064245548
99976      671     4308     3.5  1065111985
99977      671     4880     4.0  1065111973
99978      671     4886     5.0  1064245488
99979      671     4896     5.0  1065111996
99980      671     4963     4.5  1065111855
99981      671     4973     4.5  1064245471
99982      671     4993     5.0  1064245483
99983      671     4995     4.0  1064891537
99984      671     5010     2.0  1066793004
99985      671     5218     2.0  1065111990
99986      671     5299     3.0  1065112004
99987      671     5349     4.0  1065111863
99988      671     5377     4.0  1064245557
99989      671     5445     4.5  1064891627
99990      671     5464     3.0  1064891549
99991      671     5669     4.0  1063502711
99992      671     5816     4.0  1065111963
99993      671     5902     3.5  1064245507
99994      671     5952     5.0  1063502716
99995      671     5989     4.0  1064890625
99996      671     5991     4.5  1064245387
99997      671     5995     4.0  1066793014
99998      671     6212     2.5  1065149436
99999      671     6268     2.5  1065579370
100000     671     6269     4.0  1065149201
100001     671     6365     4.0  1070940363
100002     671     6385     2.5  1070979663
100003     671     6565     3.5  1074784724

[100004 rows x 4 columns]

In [20]:
#JOIN 1: Link with ratings
## Chose to merge these two tables first because of size and easy to connect with movieID
links_ratings_merge = pd.merge(links_df,ratings_df,on ="movieId")

links_rating_merge_df=pd.DataFrame(links_ratings_merge)


#links_ratings_merge
links_ratings_merge.dtypes
#links_ratings_merge.columns
#links_ratings_merge
#links_rating_merge_df

movieId        int64
imdbId         int64
tmdbId       float64
userId         int64
rating       float64
timestamp      int64
dtype: object

In [5]:
#Import 3rd data source- MOVIE METADATA 
movie_meta_file = "../ETL_Project_original_Data/movies_metadata.csv"
movie_meta= pd.read_csv(movie_meta_file)
movie_meta_df=pd.DataFrame(movie_meta)
#movie_meta_df

C:\Users\Craig\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [27]:
#Reduce columns to valuable to task
movie_meta_df_revised=movie_meta_df[["imdb_id","title","genres","vote_count","vote_average","overview",\
                                            "release_date","budget","revenue", "id","adult","spoken_languages",
                                            "original_language"]]

movie_meta_df_revised['imdbId']=pd.Series(movie_meta_df['imdb_id'].str[3: ],index=movie_meta_df.index, dtype=None)

#movie_meta_df_revised.dtypes
movie_meta_df_revised
#movie_meta_df_revised.columns

AttributeError: Can only use .str accessor with string values, which use np.object_ dtype in pandas

In [10]:
#imdb_id_copy=movie_meta_df['imdb_id'].str[3: ].copy
#imdb_id_ds=pd.DataSeries(imdb_id_copy)

movie_meta_df['imdbId']=pd.Series(movie_meta_df['imdb_id'].str[3: ],index=movie_meta_df.index, dtype=None)

#movie_meta_df.dtypes
movie_meta_df.head()
#movie_meta_df.dtypes
#movie_meta_df.columns

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,imdbId
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0,114709
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0,113497
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0,113228
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0,114885
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0,113041

In [17]:
#movie_meta_df=movie_meta_df.convert_objects(convert_numeric=True)
#movie_meta_df=movie_meta_df.convert_objects(convert_numeric=True)

movie_meta_df.dtypes

adult                     object
belongs_to_collection    float64
budget                   float64
genres                    object
homepage                  object
id                       float64
imdb_id                  float64
original_language        float64
original_title           float64
overview                  object
popularity               float64
poster_path               object
production_companies      object
production_countries     float64
release_date             float64
revenue                  float64
runtime                  float64
spoken_languages          object
status                    object
tagline                  float64
title                    float64
video                    float64
vote_average             float64
vote_count               float64
imdbId                   float64
dtype: object

In [18]:


#Merge links_ratings_merge with 
complete_date_merge = pd.merge(links_ratings_merge,movie_meta_df,on ="imdbId")
complete_date_merge

,movieId,imdbId,tmdbId,userId,rating,timestamp,adult,belongs_to_collection,budget,genres,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,1,114709,862.0,7,3.0,851866703,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,7.7,5415.0
1,1,114709,862.0,9,4.0,938629179,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,7.7,5415.0
2,1,114709,862.0,13,5.0,1331380058,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,7.7,5415.0
3,1,114709,862.0,15,2.0,997938310,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,7.7,5415.0
4,1,114709,862.0,19,3.0,855190091,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,7.7,5415.0
5,1,114709,862.0,20,3.5,1238729767,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,7.7,5415.0
6,1,114709,862.0,23,3.0,1148729853,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,7.7,5415.0
7,1,114709,862.0,26,5.0,1360087980,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,7.7,5415.0
8,1,114709,862.0,30,4.0,944943070,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,7.7,5415.0
9,1,114709,862.0,37,4.0,981308121,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,7.7,5415.0
10,1,114709,862.0,43,4.0,974768260,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,7.7,5415.0
11,1,114709,862.0,44,4.0,858707138,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,7.7,5415.0
12,1,114709,862.0,47,5.0,832228931,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,7.7,5415.0
13,1,114709,862.0,48,4.0,1318796720,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,7.7,5415.0
14,1,114709,862.0,55,3.0,855926941,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,7.7,5415.0
15,1,114709,862.0,56,4.0,1467004817,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,7.7,5415.0
16,1,114709,862.0,63,5.0,1079098216,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,7.7,5415.0
17,1,114709,862.0,67,3.0,854711770,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,7.7,5415.0
18,1,114709,862.0,68,4.0,1194741818,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,7.7,5415.0
19,1,114709,862.0,69,5.0,1366831110,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,7.7,5415.0
20,1,114709,862.0,70,5.0,853954235,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,7.7,5415.0
21,1,114709,862.0,72,3.5,1461778737,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,7.7,5415.0
22,1,114709,862.0,73,5.0,1303464840,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,7.7,5415.0
23,1,114709,862.0,75,3.0,1165607201,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,7.7,5415.0
24,1,114709,862.0,77,4.0,1163005363,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,7.7,5415.0
25,1,114709,862.0,79,2.0,1182994648,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,7.7,5415.0
26,1,114709,862.0,84,3.5,1429910800,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,7.7,5415.0
27,1,114709,862.0,86,3.0,848161799,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,7.7,5415.0
28,1,114709,862.0,87,3.0,858623186,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,7.7,5415.0
29,1,114709,862.0,89,5.0,1257620018,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,7.7,5415.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96074,136445,246641,34509.0,519,5.0,1471686897,False,NaN,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 99, 'nam...",...,NaN,0.0,63.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,7.8,12.0
96075,136447,246645,34513.0,519,5.0,1471686728,False,NaN,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 99, 'nam...",...,NaN,0.0,65.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,8.0,14.0
96076,136592,113112,196257.0,200,1.5,1438020227,False,NaN,0.0,"[{'id': 10770, 'name': 'TV Movie'}, {'id': 35,...",...,NaN,0.0,86.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,5.2,11.0
96077,137403,259017,102016.0,652,3.5,1442082603,False,NaN,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10769, 'n...",...,NaN,0.0,105.0,[],Released,NaN,NaN,0.0,0.0,0.0
96078,139130,465316,62931.0,73,4.0,1437711245,False,NaN,0.0,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",...,NaN,0.0,125.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,7.3,63.0
96079,139620,263438,81549.0,270,4.0,1469278481,False,NaN,0.0,"[{'id': 10751, 'name': 'Family'}, {'id': 18, '...",...,NaN,0.0,107.0,"[{'iso_639_1': 'tr', 'name': 'Türkçe'}]",Released,NaN,NaN,0.0,8.0,11.0
96080,140265,246643,25161.0,519,5.0,1471686899,False,NaN,0.0,"[{'id': 99, 'name': 'Documentary'}, {'id': 35,...",...,NaN,0.0,59.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,7.8,12.0
96081,140739,419722,41423.0,652,5.0,1439585580,False,NaN,0.0,"[{'id': 18, 'name': 'Drama'}]",...,NaN,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,3.3,3.0
96082,140741,218298,41636.0,652,5.0,1439585771,False,NaN,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",...,NaN,0.0,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,5.6,5.0
96083,140743,173906,19654.0,652,5.0,1439586481,False,NaN,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10769, 'n...",...,NaN,0.0,87.0,"[{'iso_639_1': 'fr', 'name': 'Français'}]",Released,NaN,NaN,0.0,5.5,9.0
96084,140745,312297,19828.0,652,5.0,1439586605,False,NaN,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",...,NaN,0.0,87.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,3.0,2.0
96085,140749,455299,23427.0,652,5.0,1439586708,False,NaN,25000.0,"[{'id': 35, 'name': 'Comedy'}]",...,NaN,0.0,87.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,5.0,2.0
96086,140751,466669,32633.0,652,5.0,1439586931,False,NaN,0.0,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",...,NaN,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,5.3,8.0
96087,140755,494253,77583.0,652,5.0,1439587113,False,NaN,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",...,NaN,0.0,97.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,5.8,4.0
96088,140761,300996,29063.0,652,5.0,1439587262,False,NaN,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",...,NaN,0.0,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,6.0,1.0
96089,140880,838192,60850.0,652,4.0,1440029031,False,NaN,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10769, '...",...,NaN,1101480.0,105.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}]",Released,NaN,NaN,0.0,6.6,8.0
96090,141124,396587,37091.0,652,5.0,1440273477,False,NaN,0.0,"[{'id': 18, 'name': 'Drama'}]",...,NaN,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,5.3,4.0
96091,141749,810819,306819.0,547,4.0,1468077724,False,NaN,15000000.0,"[{'id': 18, 'name': 'Drama'}]",...,NaN,64191523.0,120.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,NaN,0.0,7.4,1689.0
96092,141886,116729,5900.0,450,5.0,1475737051,False,NaN,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",...,NaN,0.0,103.0,"[{'iso_639_1': 'nl', 'name': 'Nederlands'}]",Released,NaN,NaN,0.0,7.0,3.0
96093,142192,48064,65014.0,547,3.5,1442199101,False,NaN,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",...,NaN,0.0,97.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,5.3,6.0
96094,143859,475290,270487.0,655,3.0,1470075909,False,NaN,22000000.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",...,NaN,63647656.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,5.7,1338.0
96095,145307,102996,45147.0,457,2.5,1471388180,False,NaN,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",...,NaN,7683267.0,84.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,5.6,7.0
96096,147037,367097,92326.0,652,5.0,1447808622,False,NaN,0.0,"[{'id': 35, 'name': 'Comedy'}]",...,NaN,0.0,96.0,[],Released,NaN,NaN,0.0,5.4,5.0
96097,152057,790770,316000.0,15,0.5,1465793700,False,NaN,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",...,NaN,3460466.0,100.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,6.7,74.0
96098,152173,88263,92060.0,262,3.0,1466556504,False,NaN,1100000.0,"[{'id': 27, 'name': 'Horror'}, {'id': 10402, '...",...,NaN,0.0,13.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,8.1,90.0
96099,152844,165473,104548.0,73,4.0,1476080611,False,NaN,0.0,"[{'id': 27, 'name': 'Horror'}, {'id': 10769, '...",...,NaN,0.0,135.0,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,NaN,NaN,0.0,8.6,11.0
96100,159462,155350,26677.0,73,3.0,1469772608,False,NaN,0.0,"[{'id': 27, 'name': 'Horror'}]",...,NaN,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,5.0,20.0
96101,160563,918940,258489.0,15,1.0,1469330270,False,NaN,180000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",...,NaN,356743061.0,109.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,5.5,2488.0
96102,160563,918940,258489.0,287,4.0,1469161444,False,NaN,180000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",...,NaN,356743061.0,109.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,NaN,0.0,5.5,2488.0
96103,161944,255313,159550.0,287,5.0,1470167824,False,NaN,8000000.0,"[{'id': 18, 'name': 'Drama'}]",...,NaN,0.0,85.0,[],Released,NaN,NaN,0.0,7.0,1.0

In [19]:
complete_date_merge_title=complete_date_merge.set_index('title')
#Compare Columns before MERGING
complete_date_merge_title
#movie_meta_df_revised.columns

,movieId,imdbId,tmdbId,userId,rating,timestamp,adult,belongs_to_collection,budget,genres,...,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,video,vote_average,vote_count
title,,,,,,,,,,,,,,,,,,,,,
NaN,1,114709,862.0,7,3.0,851866703,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,7.7,5415.0
NaN,1,114709,862.0,9,4.0,938629179,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,7.7,5415.0
NaN,1,114709,862.0,13,5.0,1331380058,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,7.7,5415.0
NaN,1,114709,862.0,15,2.0,997938310,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,7.7,5415.0
NaN,1,114709,862.0,19,3.0,855190091,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,7.7,5415.0
NaN,1,114709,862.0,20,3.5,1238729767,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,7.7,5415.0
NaN,1,114709,862.0,23,3.0,1148729853,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,7.7,5415.0
NaN,1,114709,862.0,26,5.0,1360087980,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,7.7,5415.0
NaN,1,114709,862.0,30,4.0,944943070,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,7.7,5415.0
NaN,1,114709,862.0,37,4.0,981308121,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,7.7,5415.0
NaN,1,114709,862.0,43,4.0,974768260,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,7.7,5415.0
NaN,1,114709,862.0,44,4.0,858707138,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,7.7,5415.0
NaN,1,114709,862.0,47,5.0,832228931,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,7.7,5415.0
NaN,1,114709,862.0,48,4.0,1318796720,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,7.7,5415.0
NaN,1,114709,862.0,55,3.0,855926941,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,7.7,5415.0
NaN,1,114709,862.0,56,4.0,1467004817,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,7.7,5415.0
NaN,1,114709,862.0,63,5.0,1079098216,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,7.7,5415.0
NaN,1,114709,862.0,67,3.0,854711770,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,7.7,5415.0
NaN,1,114709,862.0,68,4.0,1194741818,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,7.7,5415.0
NaN,1,114709,862.0,69,5.0,1366831110,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,7.7,5415.0
NaN,1,114709,862.0,70,5.0,853954235,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,7.7,5415.0
NaN,1,114709,862.0,72,3.5,1461778737,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,7.7,5415.0
NaN,1,114709,862.0,73,5.0,1303464840,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,7.7,5415.0
NaN,1,114709,862.0,75,3.0,1165607201,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,7.7,5415.0
NaN,1,114709,862.0,77,4.0,1163005363,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,7.7,5415.0
NaN,1,114709,862.0,79,2.0,1182994648,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,7.7,5415.0
NaN,1,114709,862.0,84,3.5,1429910800,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,7.7,5415.0
NaN,1,114709,862.0,86,3.0,848161799,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,7.7,5415.0
NaN,1,114709,862.0,87,3.0,858623186,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,7.7,5415.0
NaN,1,114709,862.0,89,5.0,1257620018,False,NaN,30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",...,NaN,NaN,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,7.7,5415.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
NaN,136445,246641,34509.0,519,5.0,1471686897,False,NaN,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 99, 'nam...",...,NaN,NaN,0.0,63.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,7.8,12.0
NaN,136447,246645,34513.0,519,5.0,1471686728,False,NaN,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 99, 'nam...",...,NaN,NaN,0.0,65.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,8.0,14.0
NaN,136592,113112,196257.0,200,1.5,1438020227,False,NaN,0.0,"[{'id': 10770, 'name': 'TV Movie'}, {'id': 35,...",...,NaN,NaN,0.0,86.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,5.2,11.0
NaN,137403,259017,102016.0,652,3.5,1442082603,False,NaN,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10769, 'n...",...,NaN,NaN,0.0,105.0,[],Released,NaN,0.0,0.0,0.0
NaN,139130,465316,62931.0,73,4.0,1437711245,False,NaN,0.0,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",...,NaN,NaN,0.0,125.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,7.3,63.0
NaN,139620,263438,81549.0,270,4.0,1469278481,False,NaN,0.0,"[{'id': 10751, 'name': 'Family'}, {'id': 18, '...",...,NaN,NaN,0.0,107.0,"[{'iso_639_1': 'tr', 'name': 'Türkçe'}]",Released,NaN,0.0,8.0,11.0
NaN,140265,246643,25161.0,519,5.0,1471686899,False,NaN,0.0,"[{'id': 99, 'name': 'Documentary'}, {'id': 35,...",...,NaN,NaN,0.0,59.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,7.8,12.0
NaN,140739,419722,41423.0,652,5.0,1439585580,False,NaN,0.0,"[{'id': 18, 'name': 'Drama'}]",...,NaN,NaN,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,3.3,3.0
NaN,140741,218298,41636.0,652,5.0,1439585771,False,NaN,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",...,NaN,NaN,0.0,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,5.6,5.0
NaN,140743,173906,19654.0,652,5.0,1439586481,False,NaN,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10769, 'n...",...,NaN,NaN,0.0,87.0,"[{'iso_639_1': 'fr', 'name': 'Français'}]",Released,NaN,0.0,5.5,9.0
NaN,140745,312297,19828.0,652,5.0,1439586605,False,NaN,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",...,NaN,NaN,0.0,87.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,3.0,2.0
NaN,140749,455299,23427.0,652,5.0,1439586708,False,NaN,25000.0,"[{'id': 35, 'name': 'Comedy'}]",...,NaN,NaN,0.0,87.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,5.0,2.0
NaN,140751,466669,32633.0,652,5.0,1439586931,False,NaN,0.0,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",...,NaN,NaN,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,5.3,8.0
NaN,140755,494253,77583.0,652,5.0,1439587113,False,NaN,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",...,NaN,NaN,0.0,97.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,5.8,4.0
NaN,140761,300996,29063.0,652,5.0,1439587262,False,NaN,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",...,NaN,NaN,0.0,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,6.0,1.0
NaN,140880,838192,60850.0,652,4.0,1440029031,False,NaN,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10769, '...",...,NaN,NaN,1101480.0,105.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}]",Released,NaN,0.0,6.6,8.0
NaN,141124,396587,37091.0,652,5.0,1440273477,False,NaN,0.0,"[{'id': 18, 'name': 'Drama'}]",...,NaN,NaN,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,5.3,4.0
NaN,141749,810819,306819.0,547,4.0,1468077724,False,NaN,15000000.0,"[{'id': 18, 'name': 'Drama'}]",...,NaN,NaN,64191523.0,120.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,0.0,7.4,1689.0
NaN,141886,116729,5900.0,450,5.0,1475737051,False,NaN,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",...,NaN,NaN,0.0,103.0,"[{'iso_639_1': 'nl', 'name': 'Nederlands'}]",Released,NaN,0.0,7.0,3.0
NaN,142192,48064,65014.0,547,3.5,1442199101,False,NaN,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",...,NaN,NaN,0.0,97.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,5.3,6.0
NaN,143859,475290,270487.0,655,3.0,1470075909,False,NaN,22000000.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",...,NaN,NaN,63647656.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,5.7,1338.0
NaN,145307,102996,45147.0,457,2.5,1471388180,False,NaN,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",...,NaN,NaN,7683267.0,84.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,5.6,7.0
NaN,147037,367097,92326.0,652,5.0,1447808622,False,NaN,0.0,"[{'id': 35, 'name': 'Comedy'}]",...,NaN,NaN,0.0,96.0,[],Released,NaN,0.0,5.4,5.0
NaN,152057,790770,316000.0,15,0.5,1465793700,False,NaN,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",...,NaN,NaN,3460466.0,100.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,6.7,74.0
NaN,152173,88263,92060.0,262,3.0,1466556504,False,NaN,1100000.0,"[{'id': 27, 'name': 'Horror'}, {'id': 10402, '...",...,NaN,NaN,0.0,13.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,8.1,90.0
NaN,152844,165473,104548.0,73,4.0,1476080611,False,NaN,0.0,"[{'id': 27, 'name': 'Horror'}, {'id': 10769, '...",...,NaN,NaN,0.0,135.0,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,NaN,0.0,8.6,11.0
NaN,159462,155350,26677.0,73,3.0,1469772608,False,NaN,0.0,"[{'id': 27, 'name': 'Horror'}]",...,NaN,NaN,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,5.0,20.0
NaN,160563,918940,258489.0,15,1.0,1469330270,False,NaN,180000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",...,NaN,NaN,356743061.0,109.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,5.5,2488.0
NaN,160563,918940,258489.0,287,4.0,1469161444,False,NaN,180000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",...,NaN,NaN,356743061.0,109.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,0.0,5.5,2488.0
NaN,161944,255313,159550.0,287,5.0,1470167824,False,NaN,8000000.0,"[{'id': 18, 'name': 'Drama'}]",...,NaN,NaN,0.0,85.0,[],Released,NaN,0.0,7.0,1.0